### PR TITLE
Parametrize forced printing

### PR DESCRIPTION
**Pull request by cemkavuklu**
This PR makes forced printing switchable so that it can be turned off at will.

P.S. Single quote to double quote conversion is the work of `black` formatter. You can keep or revert back as you wish.

### CODE REVIEW

**Comment by ritajie** [comment]
@cemkavuklu Thanks for your PR!

There's just one problem: now `return_it` seems to be meaningless - when passing `return_it=False`, the program does nothing.

I have a suggestion:
1. Continue to keep `return_it`, and the default value also continues to be `False`
2. Added `print_it` parameter, the default value is `True`

Just like that:
```python
def parse(request_or_response, compressed=False, verify=True, return_it=False, print_it=True):
```

The advantages of doing this are:
1. After the old user upgrades, the effect remains the same: continue to print to standard output
2. The effect you expect can also be satisfied by passing parameters

---

WDYT? 🙌

**Comment by ritajie** [comment]
Related issue: https://github.com/ritajie/requests_to_curl/issues/2

**Comment by cemkavuklu** [comment]
You are right. Added `print_it` to the signature.

**Comment by ritajie** [comment]
@cemkavuklu It looks perfect!

I'll do a more detailed test tonight or tomorrow and then push these code updates to pypi.
I'll let you know here when this is done.

Thanks again for your contribution 😊

**Comment by cemkavuklu** [comment]
My pleasure 😀

Have a great day.

**Pull request merged**
